global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # Need enterprise license key
  # - job_name: 'litellm'
  #   static_configs:
  #     - targets: ['litellm:4000']
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
